//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dberzervasyonTable
    {
        public int rezervasyonID { get; set; }
        public Nullable<int> seferID { get; set; }
        public Nullable<int> m_ID { get; set; }
        public Nullable<byte> kolTuknumara { get; set; }
        public Nullable<decimal> ucreT { get; set; }
        public Nullable<System.DateTime> rezervasyonTarihi { get; set; }
    
        public virtual dbmusTeriTable dbmusTeriTable { get; set; }
        public virtual dbseferTable dbseferTable { get; set; }
    }
}
