//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbkasaTable
    {
        public short ID { get; set; }
        public Nullable<decimal> Kasa { get; set; }
    }
}
