//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbmusTeriTable
    {
        public dbmusTeriTable()
        {
            this.dberzervasyonTable = new HashSet<dberzervasyonTable>();
        }
    
        public int m_ID { get; set; }
        public string m_ad { get; set; }
        public string m_soyad { get; set; }
        public Nullable<bool> cinsiyeT { get; set; }
        public Nullable<byte> phone { get; set; }
        public string mail { get; set; }
        public Nullable<byte> kimlikno { get; set; }
    
        public virtual ICollection<dberzervasyonTable> dberzervasyonTable { get; set; }
    }
}
