//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dboTobusTable
    {
        public dboTobusTable()
        {
            this.dbseferTable = new HashSet<dbseferTable>();
        }
    
        public int busID { get; set; }
        public string marka { get; set; }
        public string plaka { get; set; }
        public bool[] kolTuksayısı { get; set; }
        public Nullable<byte> kolTuksayisi { get; set; }
    
        public virtual ICollection<dbseferTable> dbseferTable { get; set; }
    }
}
