//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbseferTable
    {
        public dbseferTable()
        {
            this.dberzervasyonTable = new HashSet<dberzervasyonTable>();
        }
    
        public int seferID { get; set; }
        public Nullable<int> busID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<System.DateTime> daTe { get; set; }
        public Nullable<decimal> fiyaT { get; set; }

        public virtual void FiyatHesapla(int? mesafe_KM) { }

        public virtual string SeferBilgisi()
        {
            return $"{busID} - {sehirID} | {daTe:dd.MM.yyyy} | {fiyaT:C}";
        }
    
        public virtual ICollection<dberzervasyonTable> dberzervasyonTable { get; set; }
        public virtual dboTobusTable dboTobusTable { get; set; }
        public virtual dbsehirTable dbsehirTable { get; set; }
    }
}
