//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsehirTable
    {
        public dbsehirTable()
        {
            this.dbseferTable = new HashSet<dbseferTable>();
        }
    
        public int sehirID { get; set; }
        public string sehir1 { get; set; }
        public string sehir2 { get; set; }
        public Nullable<int> mesafe_KM { get; set; }
    
        public virtual ICollection<dbseferTable> dbseferTable { get; set; }
    }
}
