//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarihler
    {
        public short daTeID { get; set; }
        public Nullable<byte> Gun { get; set; }
        public Nullable<byte> Ay { get; set; }
        public Nullable<short> Yil { get; set; }
    }
}
